repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      #- id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
      - id: requirements-txt-fixer
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        files: ^server/
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1 # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        files: ^front-end/
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.32.0 # Use the sha / tag you want to point at
    hooks:
      - id: eslint
        files: ^front-end/.*\.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        args: [-c, front-end/.eslintrc-pre-commit.json, --fix]
        additional_dependencies:
          - eslint@7.32.0
          - "@angular-eslint/eslint-plugin@12.7.0"
          - "@angular-eslint/eslint-plugin-template@12.7.0"
          - "@angular-eslint/template-parser@12.7.0"
          - "@typescript-eslint/parser@4.28.2"
          - "@typescript-eslint/eslint-plugin@4.28.2"
          - "eslint-config-prettier@8.3.0"
          - "eslint-plugin-sort-imports-es6-autofix@0.6.0"
