version: '3.8'

services:
  proxy:
    build: proxy
    image: asennyey/proxy
  server:
    build: server
    image: asennyey/tutor-center
  front-end:
    build: front-end
    image: asennyey/front-end
