version: '3.8'

services:
  nginx:
    build: nginx
    image: asennyey/proxy
  server:
    build: server
    image: asennyey/tutor-center
  front-end:
    build: front-end
    image: asennyey/front-end
