version: '3.8'

services:
  server:
    restart: always
    image: asennyey/tutor-center
    build:
      context: ./server
      dockerfile: Dockerfile
    command: gunicorn tutor_center.wsgi --bind 0.0.0.0:8000 --worker-tmp-dir /dev/shm --workers=2 --threads=4
    volumes:
      - static_volume:/home/app/web/staticfiles
      - ./server/logs:/var/log
    env_file: server/.env
    expose:
      - 8000
    depends_on:
      - redis
  proxy:
    restart: always
    image: asennyey/proxy
    build: ./proxy
    volumes:
      - ./proxy/logs:/var/log/nginx
      - static_volume:/home/app/web/staticfiles
    ports:
      - 3000:80
    depends_on:
      - server
      - front-end
  front-end:
    restart: always
    image: asennyey/front-end
    build: ./front-end
    expose:
     - 80
  log-rotate:
    restart: always
    image: blacklabelops/logrotate
    volumes:
      - ./nginx/logs:/var/log/nginx
    environment:
      - LOGS_DIRECTORIES=/var/log/nginx
    depends_on:
      - proxy
  redis:
    restart: always
    image: redis:6.2-alpine3.15
    volumes:
      - redis_storage:/data
    expose:
      - 6379

volumes:
  static_volume:
  redis_storage:
