version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: gunicorn tutor_center.wsgi --bind 0.0.0.0:8000 --worker-tmp-dir /dev/shm --workers=2 --threads=4
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8000:80
    depends_on:
      - server
  front-end:
    build: ./front-end
    ports:
     - 8080:80

volumes:
  static_volume:
