version: '3.8'

services:
  proxy:
    build: proxy
    image: "${REGISTRY}/${IMAGE_NAME}:proxy"
  server:
    build: server
    image: "${REGISTRY}/${IMAGE_NAME}:server"
  front-end:
    build: front-end
    image: "${REGISTRY}/${IMAGE_NAME}:front-end"
