# Generated by Django 3.2.11 on 2022-02-05 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tutor",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_coord", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("modified_time", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=20)),
            ],
            options={
                "ordering": ["-created_time"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TutoringRequest",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("modified_time", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("closed_time", models.DateTimeField(default=None)),
                ("description", models.CharField(max_length=2000)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WAITING", "WAITING"),
                            ("INPROGRESS", "INPROGRESS"),
                            ("COMPLETE", "COMPLETE"),
                        ],
                        default="WAITING",
                        max_length=20,
                    ),
                ),
                (
                    "requested_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tutor_center.course",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_time"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="tutor",
            name="courses",
            field=models.ManyToManyField(to="tutor_center.Course"),
        ),
    ]
