#!/bin/bash
VIRTUAL_ENV="env"
BASE_DIR=$(git rev-parse --show-toplevel)
cd "$BASE_DIR"
cd server
python3 -m venv "$VIRTUAL_ENV"
source "$VIRTUAL_ENV/bin/activate"
pip install -r requirements.txt
deactivate

cd "$BASE_DIR"
cd front-end
npm i
ng build --prod
